### ISSUE TITLE
Drawflow in Angualr 

### ISSUE THREAD

**Issue by Nagaraj172004** [jerosoler/Drawflow#751]
im implementing the DrawFlow component to Angular project , draflow works ok but when i drag in and drag out the node im getting this error, 
Uncaught TypeError: Cannot read properties of null (reading 'clientWidth')
at addNodeToDrawFlow ((index):137:41)
at drop ((index):128:9)
at HTMLDivElement.ondrop ((index):336:9)

can anyone tell me where i mistake , Thanks in advance , Pls check attached snap below , Thank you

![image](https://github.com/jerosoler/Drawflow/assets/106150879/522f63ee-0457-42ab-a0cb-ad4355c80cf4)

**Comment by Nagaraj172004** [comment]
Hi @Faizi9321 glad to hear , please use the github URL above mentioned , clone the project in your system 
(using the Git command) .

step1; install node packages (npm install)
step2: install drawFlow dependencies ( npm i drawflow) 
thats all . after compile successfull open browser localhost:4200 .

i hope this answer is helpfull , Thank you..

**Comment by FaizanAwais** [comment]
I do this all but when start its nothing to show in my project and my project is typescript based.

**Comment by Nagaraj172004** [comment]
yeah based on javascript i design this project if you want typescript based function , just copy index.html function (method ) paste it in your drawflow component. For  Example : 

**HTML**

        <div class="drag-drawflow" draggable="true" (ondragstart)="drag($event)" data-node="facebook">
            <i class="fab fa-facebook"></i><span> Nagaraj</span>
 
**TS** 
        
      drag(ev) {
      if (ev.type === "touchstart") {
        mobile_item_selec = ev.target.closest(".drag-drawflow").getAttribute('data-node');
      } else {
        ev.dataTransfer.setData("node", ev.target.getAttribute('data-node'));
      }
    }
 
 i hope this answer is helpfull , Thank you

**Comment by Nagaraj172004** [comment]
any solution or suggestion for this error @jerosoler ?

**Comment by Nagaraj172004** [comment]
**HTML**

    <div class="drag-drawflow" draggable="true" (ondragstart)="drag($event)" data-node="facebook">
        <i class="fab fa-facebook"></i><span> Nagaraj</span>



**TS**
        
       drag(ev) {
        if (ev.type === "touchstart") {
           mobile_item_selec = ev.target.closest(".drag-drawflow").getAttribute('data-node');
           } else {
              ev.dataTransfer.setData("node", ev.target.getAttribute('data-node'));
        }
     }


this is my code @jerosoler , 
when i drag and drag out the Node getting error 

Cannot read properties of null (reading 'clientWidth')
at addNodeToDrawFlow ((index):137:41)
at drop ((index):128:9)
at HTMLDivElement.ondrop ((index):336:9)

**Comment by Nagaraj172004** [comment]
is it possible to provide me the Javscript code to implement Drawflow @jerosoler , i will figuare it out , if its success i will inform here lets everyone implement drawflow in there project 

Thank you !

**Comment by Nagaraj172004** [comment]
correct this code snippet is not running in javascript @jerosoler  :

Uncaught TypeError: Cannot read properties of null (reading 'clientWidth')
    at addNodeToDrawFlow ((index):172:41)
    at drop ((index):163:9)
    at HTMLDivElement.ondrop ((index):371:9)

**Comment by jerosoler** [comment]
Does the editor variable return anything?

Check if it doesn't return something.

**Comment by Nagaraj172004** [comment]
![image](https://github.com/jerosoler/Drawflow/assets/106150879/434302c1-0870-4751-a207-c5d300317eed)

![2023-08-17_17h09_37](https://github.com/jerosoler/Drawflow/assets/106150879/ff820438-7b78-4b73-b76e-f4d6317a4a2a)

please check the attached snap @jerosoler

**Comment by jerosoler** [comment]
If the variable is null, then it is not defined. I would have to see why it is not defined.

I don't know the angular framework.

I recommend you check out this repo:

https://github.com/RoyaghRamo/angular-drawflow-example


Review function "addNodeToDrawBoard" 
https://github.com/RoyaghRamo/angular-drawflow-example/blob/3d45491c458bd41607dba3c2d1c8f4c33bc3c949/src/app/drawing-board/drawing-board.component.ts#L353

**Comment by Nagaraj172004** [comment]
@jerosoler when i did these changes getting inject() must be called from an injection context (a constructor, a factory function or a field initializer).   error which is in Angular can ayone tell me why it is throwing runtime error 

ERROR Error: NG0203: inject() must be called from an injection context (a constructor, a factory function or a field initializer). Find more at https://angular.io/errors/NG0203
    at injectInjectorOnly (core.mjs:4863:15)
    at Module.ɵɵinject (core.mjs:4873:60)
    at Object.NgbModal_Factory [as factory] (ng-bootstrap.mjs:242:95)
    at R3Injector.hydrate (core.mjs:9301:35)
    at R3Injector.get (core.mjs:9189:33)
    at ChainedInjector.get (core.mjs:13007:36)
    at lookupTokenUsingModuleInjector (core.mjs:4436:39)
    at getOrCreateInjectable (core.mjs:4484:12)
    at Module.ɵɵdirectiveInject (core.mjs:10778:12)
    at NodeInjectorFactory.DrawingBoardComponent_Factory [as factory] (drawing-board.component.ts:18:35)
    
![image](https://github.com/jerosoler/Drawflow/assets/106150879/fa5862c8-918e-4b98-bea3-1499355ada84)

**Comment by Nagaraj172004** [comment]
@jerosoler any idea or sugesstion ??

**Comment by jerosoler** [comment]
I don't know the angular framework.

**Comment by Alfxjx** [comment]
hi all I make a pull request for using drawflow in angular 

https://github.com/Nagaraj172004/drawflow/pull/1

have fun using drawflow :D
